const data = [
  {
    modelNumber: "123W",
    price: "29500",
    img: require("../../assets/pianoList/piano-123W.png").default,
    from: "中国",
    color: "白色亮光(以实物为准)",
    size: "1520mm*620mm*1230mm",
    musicWire: "Roslou勒斯劳琴弦",
    plank: "纯铜脚踏/精钢脚踏",
    hammer: "德国进口榔头",
    key: "实木琴键-逐键配重工艺",
    nail: "镀钛乌金弦轴钉",
    mark: "全框铁骨工艺，一次成型，保证更大拉力",
    soundboard: "云杉实木复合精制音板",
    oilPaint: "德国无氧无污染天然酵化镜面漆",
    slowDescent: "高端内置缓降器和三角琴同款",
    action: "雷诺式击弦机",
    MovingRod: "品质天然实木联动装置",
  },

  {
    modelNumber: "126B",
    price: "36800",
    img: require("../../assets/pianoList/piano-126B.png").default,
    from: "中国",
    color: "黑色亮光(以实物为准)",
    size: "1530mm*630mm*1260mm",
    musicWire: "Roslou勒斯劳琴弦",
    plank: "纯铜脚踏/精钢脚踏",
    hammer: "德国进口榔头",
    key: "实木琴键-逐键配重工艺",
    nail: "镀钛乌金弦轴钉",
    mark: "全框铁骨工艺，一次成型，保证更大拉力",
    soundboard: "云杉实木复合精制音板",
    oilPaint: "德国无氧无污染天然酵化镜面漆",
    slowDescent: "高端内置缓降器和三角琴同款",
    action: "雷诺式击弦机",
    MovingRod: "品质天然实木联动装置",
  },

  {
    modelNumber: "126Y3",
    price: "39800",
    img: require("../../assets/pianoList/piano-126Y3.png").default,
    from: "中国",
    color: "白色亮光(以实物为准)",
    size: "1530mm*630mm*1260mm",
    musicWire: "Roslou勒斯劳琴弦",
    plank: "纯铜脚踏/精钢脚踏",
    hammer: "德国进口榔头",
    key: "实木琴键-逐键配重工艺",
    nail: "镀钛乌金弦轴钉",
    mark: "全框铁骨工艺，一次成型，保证更大拉力",
    soundboard: "云杉实木复合精制音板",
    oilPaint: "德国无氧无污染天然酵化镜面漆",
    slowDescent: "高端内置缓降器和三角琴同款",
    action: "雷诺式击弦机",
    MovingRod: "品质天然实木联动装置",
  },

  {
    modelNumber: "126Y8",
    price: "42800",
    img: require("../../assets/pianoList/piano-126Y8.png").default,
    from: "中国",
    color: "白色亮光(以实物为准)",
    size: "1530mm*630mm*1260mm",
    musicWire: "Roslou勒斯劳琴弦",
    plank: "纯铜脚踏/精钢脚踏",
    hammer: "德国进口榔头",
    key: "实木琴键-逐键配重工艺",
    nail: "镀钛乌金弦轴钉",
    mark: "全框铁骨工艺，一次成型，保证更大拉力",
    soundboard: "云杉实木复合精制音板",
    oilPaint: "德国无氧无污染天然酵化镜面漆",
    slowDescent: "高端内置缓降器和三角琴同款",
    action: "雷诺式击弦机",
    MovingRod: "品质天然实木联动装置",
  },

  {
    modelNumber: "126Y9",
    price: "43900",
    img: require("../../assets/pianoList/piano-126Y9.png").default,
    from: "中国",
    color: "白色亚光(以实物为准)",
    size: "1530mm*630mm*1260mm",
    musicWire: "Roslou勒斯劳琴弦",
    plank: "纯铜脚踏/精钢脚踏",
    hammer: "德国进口榔头",
    key: "实木琴键-逐键配重工艺",
    nail: "镀钛乌金弦轴钉",
    mark: "全框铁骨工艺，一次成型，保证更大拉力",
    soundboard: "云杉实木复合精制音板",
    oilPaint: "德国无氧无污染天然酵化镜面漆",
    slowDescent: "高端内置缓降器和三角琴同款",
    action: "雷诺式击弦机",
    MovingRod: "品质天然实木联动装置",
  },

  {
    modelNumber: "125Y1",
    price: "39800",
    img: require("../../assets/pianoList/piano-125Y1.png").default,
    from: "中国",
    color: "棕色亚光(以实物为准)",
    size: "1520mm*620mm*1250mm",
    musicWire: "Roslou勒斯劳琴弦",
    plank: "纯铜脚踏/精钢脚踏",
    hammer: "德国进口榔头",
    key: "实木琴键-逐键配重工艺",
    nail: "镀钛乌金弦轴钉",
    mark: "全框铁骨工艺，一次成型，保证更大拉力",
    soundboard: "云杉实木复合精制音板",
    oilPaint: "德国无氧无污染天然酵化镜面漆",
    slowDescent: "高端内置缓降器和三角琴同款",
    action: "雷诺式击弦机",
    MovingRod: "品质天然实木联动装置",
  },

  {
    modelNumber: "126Y2",
    price: "41800",
    img: require("../../assets/pianoList/piano-126Y2.png").default,
    from: "中国",
    color: "棕色亚光(以实物为准)",
    size: "1530mm*630mm*1260mm",
    musicWire: "Roslou勒斯劳琴弦",
    plank: "纯铜脚踏/精钢脚踏",
    hammer: "德国进口榔头",
    key: "实木琴键-逐键配重工艺",
    nail: "镀钛乌金弦轴钉",
    mark: "全框铁骨工艺，一次成型，保证更大拉力",
    soundboard: "云杉实木复合精制音板",
    oilPaint: "德国无氧无污染天然酵化镜面漆",
    slowDescent: "高端内置缓降器和三角琴同款",
    action: "雷诺式击弦机",
    MovingRod: "品质天然实木联动装置",
  },

  {
    modelNumber: "133Y7",
    price: "56800",
    img: require("../../assets/pianoList/piano-133Y7.png").default,
    from: "中国",
    color: "全雕花(以实物为准)",
    size: "1530mm*630mm*1330mm",
    musicWire: "Roslou勒斯劳琴弦",
    plank: "纯铜脚踏/精钢脚踏",
    hammer: "德国进口榔头",
    key: "实木琴键-逐键配重工艺",
    nail: "镀钛乌金弦轴钉",
    mark: "全框铁骨工艺，一次成型，保证更大拉力",
    soundboard: "云杉实木复合精制音板",
    oilPaint: "德国无氧无污染天然酵化镜面漆",
    slowDescent: "高端内置缓降器和三角琴同款",
    action: "雷诺式击弦机",
    MovingRod: "品质天然实木联动装置",
  },

  {
    modelNumber: "125Y",
    price: "38800",
    img: require("../../assets/pianoList/piano-125Y.png").default,
    from: "中国",
    color: "棕色亚光(以实物为准)",
    size: "1520mm*620mm*1250mm",
    musicWire: "Roslou勒斯劳琴弦",
    plank: "纯铜脚踏/精钢脚踏",
    hammer: "德国进口榔头",
    key: "实木琴键-逐键配重工艺",
    nail: "镀钛乌金弦轴钉",
    mark: "全框铁骨工艺，一次成型，保证更大拉力",
    soundboard: "云杉实木复合精制音板",
    oilPaint: "德国无氧无污染天然酵化镜面漆",
    slowDescent: "高端内置缓降器和三角琴同款",
    action: "雷诺式击弦机",
    MovingRod: "品质天然实木联动装置",
  },

  {
    modelNumber: "126Y1",
    price: "40800",
    img: require("../../assets/pianoList/piano-126Y1.png").default,
    from: "中国",
    color: "棕色亚光(以实物为准)",
    size: "1530mm*630mm*1260mm",
    musicWire: "Roslou勒斯劳琴弦",
    plank: "纯铜脚踏/精钢脚踏",
    hammer: "德国进口榔头",
    key: "实木琴键-逐键配重工艺",
    nail: "镀钛乌金弦轴钉",
    mark: "全框铁骨工艺，一次成型，保证更大拉力",
    soundboard: "云杉实木复合精制音板",
    oilPaint: "德国无氧无污染天然酵化镜面漆",
    slowDescent: "高端内置缓降器和三角琴同款",
    action: "雷诺式击弦机",
    MovingRod: "品质天然实木联动装置",
  },

  {
    modelNumber: "128Y",
    price: "45800",
    img: require("../../assets/pianoList/piano-128Y.png").default,
    from: "中国",
    color: "棕色亚光(以实物为准)",
    size: "1530mm*630mm*1280mm",
    musicWire: "Roslou勒斯劳琴弦",
    plank: "纯铜脚踏/精钢脚踏",
    hammer: "德国进口榔头",
    key: "实木琴键-逐键配重工艺",
    nail: "镀钛乌金弦轴钉",
    mark: "全框铁骨工艺，一次成型，保证更大拉力",
    soundboard: "云杉实木复合精制音板",
    oilPaint: "德国无氧无污染天然酵化镜面漆",
    slowDescent: "高端内置缓降器和三角琴同款",
    action: "雷诺式击弦机",
    MovingRod: "品质天然实木联动装置",
  },
];
export default data;
