const data = [
  {
    modelNumber: '123W',
    price: '29500',
    img: require('../../assets/pianoList/piano-123W.png').default,
    from: '中国',
    color: '白色亮光',
    size: '1530mm*1230mm*610mm',
    musicWire: '德国“ROSLAU”勒斯劳琴弦',
    plank: '高级镀铜踏板',
    hammer: '红木芯德国进口毛毡',
    key: '白松复合实木白键并逐键加铅',
    nail: null,
    mark: '全框铁骨工艺，一次成型，保证更大拉力',
    soundboard: '云杉实木复合精制音板',
    oilPaint: '德国无氧无污染天然酵化镜面漆',
    slowDescent: '高端内置缓降器',
    action: '雷诺式击弦机',
    MovingRod: '品质天然实木联动装置',
  },

  {
    modelNumber: '126B3',
    price: '36800',
    img: require('../../assets/pianoList/piano-126B.png').default,
    from: '中国',
    color: '黑色亮光',
    size: '1530mm*1260mm*610mm',
    musicWire: '德国“ROSLAU”勒斯劳琴弦',
    plank: '高级镀铜踏板',
    hammer: '红木芯德国进口毛毡',
    key: '白松复合实木白键并逐键加铅',
    nail: null,
    mark: '全框铁骨工艺，一次成型，保证更大拉力',
    soundboard: '云杉实木复合精制音板',
    oilPaint: '德国无氧无污染天然酵化镜面漆',
    slowDescent: '高端内置缓降器',
    action: '雷诺式击弦机',
    MovingRod: '品质天然实木联动装置',
  },

  {
    modelNumber: '126Y3',
    price: '39800',
    img: require('../../assets/pianoList/piano-126Y3.png').default,
    from: '中国',
    color: '古典白哑光',
    size: '1530mm*1260mm*610mm',
    musicWire: '德国“ROSLAU”勒斯劳琴弦',
    plank: '高级镀铜拉丝踏板',
    hammer: '德国顶级羊毛毡红木榔头',
    key: '白松复合实木白键并逐键加铅',
    nail: null,
    mark: '全框铁骨工艺，一次成型，保证更大拉力',
    soundboard: '云杉实木复合精制音板',
    oilPaint: '德国无氧无污染天然酵化哑光漆',
    slowDescent: '高端内置缓降器',
    action: '雷诺式击弦机',
    MovingRod: '品质天然实木联动装置',
  },

  {
    modelNumber: '126Y8',
    price: '42800',
    img: require('../../assets/pianoList/piano-126Y8.png').default,
    from: '中国',
    color: '白色哑光',
    size: '1530mm*1260mm*610mm',
    musicWire: '德国“ROSLAU”勒斯劳琴弦',
    plank: '高级镀铜拉丝踏板',
    hammer: '德国顶级羊毛毡红木榔头',
    key: '白松复合实木白键并逐键加铅',
    nail: null,
    mark: '全框铁骨工艺，一次成型，保证更大拉力',
    soundboard: '云杉实木复合精制音板',
    oilPaint: '德国无氧无污染天然酵化哑光漆',
    slowDescent: '高端内置缓降器',
    action: '雷诺式击弦机',
    MovingRod: '品质天然实木联动装置',
  },
  {
    modelNumber: '126Y9',
    price: '43900',
    img: require('../../assets/pianoList/piano-126Y9.png').default,
    from: '中国',
    color: '白色哑光开放',
    size: '1530mm*1260mm*610mm',
    musicWire: '德国“ROSLAU”勒斯劳琴弦',
    plank: '高级镀铜拉丝踏板',
    hammer: '德国顶级羊毛毡红木榔头',
    key: '白松复合实木白键并逐键加铅',
    nail: null,
    mark: '全框铁骨工艺，一次成型，保证更大拉力',
    soundboard: '云杉实木复合精制音板',
    oilPaint: '德国无氧无污染天然酵化镜面漆',
    slowDescent: '高端内置缓降器',
    action: '雷诺式击弦机',
    MovingRod: '品质天然实木联动装置',
  },

  {
    modelNumber: '125Y1',
    price: '39800',
    img: require('../../assets/pianoList/piano-125Y1.png').default,
    from: '中国',
    color: '棕色亚光',
    size: '1500mm*1250mm*610mm',
    musicWire: '德国“ROSLAU”勒斯劳琴弦',
    plank: '高级镀铜踏板',
    hammer: '德国顶级羊毛毡红木榔头',
    key: '白松复合实木白键并逐键加铅',
    nail: null,
    mark: '翻砂蝶形铁骨工艺，一次成型',
    soundboard: '云杉实木复合精制音板',
    oilPaint: '德国无氧无污染天然酵化镜面漆',
    slowDescent: '高端内置缓降器',
    action: '雷诺式击弦机',
    MovingRod: '品质天然实木联动装置',
  },

  {
    modelNumber: '126Y2',
    price: '41800',
    img: require('../../assets/pianoList/piano-126Y2.png').default,
    from: '中国',
    color: '棕色亚光',
    size: '1500mm*1260mm*610mm',
    musicWire: '德国“ROSLAU”勒斯劳琴弦',
    plank: '高级镀铜踏板',
    hammer: '德国顶级羊毛毡红木榔头',
    key: '白松复合实木白键并逐键加铅',
    nail: null,
    mark: '翻砂蝶形铁骨工艺，一次成型',
    soundboard: '云杉实木复合精制音板',
    oilPaint: '德国无氧无污染天然酵化镜面漆',
    slowDescent: '高端内置缓降器',
    action: '雷诺式击弦机',
    MovingRod: '品质天然实木联动装置',
  },

  {
    modelNumber: '133Y7',
    price: '56800',
    img: require('../../assets/pianoList/piano-133Y7.png').default,
    from: '中国',
    color: '棕色亚光 古典雕花',
    size: '1520mm*1330mm*630mm',
    musicWire: '德国“ROSLAU”勒斯劳琴弦',
    plank: '高级镀铜拉丝踏板',
    hammer: '德国纯进口FFW榔头',
    key: '白松复合实木白键并逐键加铅',
    nail: null,
    mark: '翻砂蝶形铁骨工艺，一次成型',
    soundboard: '云杉实木复合精制音板',
    oilPaint: '德国无氧无污染天然酵化哑光漆',
    slowDescent: '高端内置缓降器',
    action: '雷诺式击弦机',
    MovingRod: '品质天然实木联动装置',
  },

  {
    modelNumber: '125Y',
    price: '38800',
    img: require('../../assets/pianoList/piano-125Y.png').default,
    from: '中国',
    color: '仿古亚',
    size: '1530mm*1250mm*610mm',
    musicWire: '德国“ROSLAU”勒斯劳琴弦',
    plank: '高级镀铜拉丝踏板',
    hammer: '德国顶级羊毛毡红木榔头',
    key: '白松复合实木白键并逐键加铅',
    nail: null,
    mark: '全框铁骨工艺，一次成型，保证更大拉力',
    soundboard: '云杉实木复合精制音板',
    oilPaint: '德国无氧无污染天然酵化哑光漆',
    slowDescent: '高端内置缓降器',
    action: '雷诺式击弦机',
    MovingRod: '品质天然实木联动装置',
  },
  {
    modelNumber: '126Y1',
    price: '40800',
    img: require('../../assets/pianoList/piano-126Y1.png').default,
    from: '中国',
    color: '古典亚',
    size: '1530mm*1260mm*610mm',
    musicWire: '德国“ROSLAU”勒斯劳琴弦',
    plank: '高级镀铜拉丝踏板',
    hammer: '德国顶级羊毛毡红木榔头',
    key: '白松复合实木白键并逐键加铅',
    nail: null,
    mark: '全框铁骨工艺，一次成型，保证更大拉力',
    soundboard: '云杉实木复合精制音板',
    oilPaint: '德国无氧无污染天然酵化哑光漆',
    slowDescent: '高端内置缓降器',
    action: '雷诺式击弦机',
    MovingRod: '品质天然实木联动装置',
  },
  {
    modelNumber: '128Y',
    price: '45800',
    img: require('../../assets/pianoList/piano-128Y.png').default,
    from: '中国',
    color: '古典亚',
    size: '1530mm*1280mm*610mm',
    musicWire: '德国“ROSLAU”勒斯劳琴弦', //琴弦
    plank: '高级镀铜拉丝踏板', //踏板
    hammer: '德国纯进口FFW榔头', //榔头
    key: '白松复合实木白键并逐键加铅', //琴键
    nail: null, //弦轴钉
    mark: '全框铁骨工艺，一次成型，保证更大拉力', //马克
    soundboard: '云杉实木复合精制音板', //音板
    oilPaint: '德国无氧无污染天然酵化哑光漆', //油漆
    slowDescent: '高端内置缓降器', //缓降
    action: '雷诺式击弦机', //击弦机
    MovingRod: '品质天然实木联动装置', //联动杆
  },
]
export default data
